Repository voiceflow/libs, pull requests merged in 2021-12, with the labels that each got.

#133 feat: export TraceType In Trace (VF-000)
  packages/base-types/src/trace/index.ts
Labels: changes requested

#134 feat: utils updates (VF-000)
  packages/common/src/utils/functional.ts
Labels: ready to merge

#137 feat: support batch for segment tracking (VF-2464)
  packages/api-sdk/src/resources/analytics.ts
  packages/api-sdk/tests/resources/analytics.unit.ts
Labels: ready for review

#135 fix: capture v2 (VF-2456)
  packages/alexa-types/src/node/capture.ts
  packages/alexa-types/src/node/captureV2.ts
  packages/alexa-types/src/node/index.ts
  packages/base-types/src/node/capture.ts
  packages/base-types/src/node/captureV2.ts
  packages/base-types/src/node/constants.ts
  packages/base-types/src/node/index.ts
  packages/chat-types/src/node/capture.ts
  packages/chat-types/src/node/captureV2.ts
  packages/chat-types/src/node/index.ts
  packages/general-types/src/node/capture.ts
  packages/general-types/src/node/captureV2.ts
  packages/general-types/src/node/index.ts
  packages/google-types/src/node/capture.ts
  packages/google-types/src/node/captureV2.ts
  packages/google-types/src/node/index.ts
  packages/voice-types/src/node/capture.ts
  packages/voice-types/src/node/captureV2.ts
  packages/voice-types/src/node/index.ts
Labels: ready to merge

#141 fix: google model version
  packages/google-types/src/version/index.ts
Labels: ready for review
