Repository voiceflow/libs, pull requests merged in 2021-09, with the labels that each got.

#33 fix: add type to debug (VF-1294)
  packages/base-types/src/trace/index.ts
Labels: ready to merge

#67 feat(general-types): add PlatformType and TTSPlatformType (VF-1544)
  packages/general-types/src/constants/index.ts
  packages/general-types/src/constants/platformType.ts
Labels: ready for review

#70 feat: added const for default voices (VF-000)
  packages/google-types/src/constants/voices.ts
Labels: ready for review

#71 fix: rename dialogflow es const (VF-1545)
  packages/general-types/src/constants/platformType.ts
Labels: ready for review, autorebase:opt-in

#72 feat: add topics types (VF-1826)
  packages/api-sdk/src/models/diagram.ts
  packages/api-sdk/src/models/version.ts
  packages/base-types/src/node/component.ts
  packages/base-types/src/node/constants.ts
  packages/base-types/src/node/jump.ts
Labels: autorebase:opt-in

#73 feat: add gif loop options (VF-1779)
  packages/base-types/src/node/visual.ts
Labels: blocked, ready for review, autorebase:opt-in

#75 feat: update fields and locales for dialogflow (VF-1311)
  packages/google-dfes-types/src/constants/locales.ts
  packages/google-dfes-types/src/constants/voices.ts
  packages/google-types/src/constants/voices.ts
Labels: ready for review, autorebase:opt-in

#78 feat: add no reply response trace (VF-1901)
  packages/base-types/src/node/utils/trace.ts
  packages/base-types/src/trace/index.ts
Labels: ready for review

#77 feat: support entities as pre-built entitiy types (VF-1330)
  packages/google-dfes-types/src/constants/slots.ts
Labels: ready to merge, autorebase:opt-in
