Repository voiceflow/libs, pull requests merged in 2022-01, with the labels that each got.

#143 fix: set metrics access to public (VF-000)
  packages/metrics/package.json
Labels: ready for review

#147 fix: use stricter type for `MetricsAsserter` constructor (VF-000)
  packages/metrics/src/testing/MetricsAsserter.ts
Labels: ready for review

#148 fix: improve typings of configs in `MetricsAsserter` (VF-000)
  packages/metrics/src/testing/MetricsAsserter.ts
  packages/metrics/src/testing/createBaseConfig.ts
Labels: in review, ready for review

#151 chore(deps-dev): add resolution for strip-ansi (VF-2629)
  package.json
  packages/api-sdk/package.json
  packages/api-sdk/yarn.lock
  packages/common/package.json
  packages/common/yarn.lock
  packages/metrics/package.json
  packages/metrics/yarn.lock
  yarn.lock
Labels: ready for review

#149 feat: add props for message delay (VF-000)
  packages/base-types/src/models/project.ts
  packages/base-types/src/node/text.ts
Labels: ready for review

#154 chore(deps): update axios (VF-2629)
  packages/api-sdk/package.json
  packages/api-sdk/src/fetch.ts
  packages/api-sdk/tests/fetch.unit.ts
  packages/metrics/package.json
  yarn.lock
Labels: ready for review

#146 feat: merge batchTrack and track methods into track (VF-2464)
  packages/api-sdk/src/resources/analytics.ts
  packages/api-sdk/tests/resources/analytics.unit.ts
Labels: ready for review

#160 fix: move delay to general setting types (VF-000)
  .gitignore
  packages/base-types/src/models/project.ts
  packages/general-types/src/version/settings.ts
Labels: ready for review

#161 fix: getProto return data type update (VF-000)
  packages/base-types/src/models/version.ts
Labels: ready for review

#162 fix: move to chat types (VF-000)
  packages/chat-types/src/version/settings.ts
  packages/general-types/src/version/settings.ts
Labels: ready for review

#164 fix: downgrade slate (VF-000)
  packages/base-types/package.json
  yarn.lock
Labels: ready for review

#166 fix: default delay to 1500ms (VF-000)
  packages/chat-types/src/version/settings.ts
Labels: ready for review

#167 feat: add `hex2abc` function (VF-000)
  packages/common/src/crypto/hex2abc.ts
  packages/common/tests/crypto/hex2abc.ts
Labels: ready to merge

#163 feat: added a murmurhash3 hash method to common (VF-2617)
  packages/common/package.json
  packages/common/src/crypto/murmurhash.ts
  packages/common/tests/crypto/murmuhash.unit.ts
Labels: unable-auto-rebase

#168 fix: entity filling trace (VF-2728)
  packages/base-types/src/node/utils/trace.ts
  packages/base-types/src/trace/index.ts
Labels: ready for review

#171 fix: yarn.lock update (VF-2617)
  yarn.lock
Labels: ready to merge

#172 fix: utterance permutations (VF-000)
  packages/common/src/utils/intent.ts
  packages/common/tests/fixtures/name.json
  packages/common/tests/utils/intent.unit.ts
  packages/common/tsconfig.json
Labels: ready for review

#175 fix: mapping and utilities (VF-2613)
  packages/alexa-types/src/constants/index.ts
  packages/alexa-types/src/constants/intents.ts
  packages/alexa-types/src/constants/mappings.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/intent.ts
  packages/common/src/utils/slot.ts
Labels: ready for review

#174 feat: add message delay to google dfes (VF-000)
  packages/chat-types/src/version/settings.ts
  packages/google-dfes-types/package.json
  packages/google-dfes-types/src/version/settings.ts
Labels: ready for review

#178 fix: update googleapis version (VF-2699)
  packages/google-types/package.json
  yarn.lock
Labels: ready to merge
